63 move testing stubs to libstesting = libstesting
takimbirprojeler/eticaret.backend.node pull request #64
Opened 2023-02-27 18:18 UTC by KerimCETINBAS

RESOLVED #63

2023-03-01 15:39 UTC, caglarcercinli requested changes

2023-03-01 15:39 UTC, caglarcercinli commented on yarn.lock
>    dependencies:
yarn.lock should be on gitignore. agree?

2023-03-02 20:04 UTC, KerimCETINBAS commented on yarn.lock
>    dependencies:
its actually ignored. i dont know why still git doesn't ignore it

2023-03-04 20:55 UTC, caglarcercinli approved these changes

2023-03-04 20:56 UTC, merged